# Generated by Django 3.2.9 on 2021-12-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservations',
            index=models.Index(fields=['dog_1_arrival', 'dog_1_departure', 'dog_2_arrival', 'dog_2_departure', 'dog_3_arrival', 'dog_3_departure', 'dog_4_arrival', 'dog_4_departure', 'dog_5_arrival', 'dog_5_departure'], name='administrat_dog_1_a_6ce75f_idx'),
        ),
    ]
