# Generated by Django 3.2.9 on 2021-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_reservations_administrat_dog_1_a_6ce75f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parks',
            name='name',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
