# Generated by Django 3.2.9 on 2021-12-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_parks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='dog_2_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='dog_2_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='dog_3_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='dog_3_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='dog_4_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='dog_4_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='dog_5_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='dog_5_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
