# Generated by Django 3.2.9 on 2021-12-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_dogs_transponder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='transponder',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
