# Generated by Django 3.2.9 on 2021-12-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_dogs_transponder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
