# Generated by Django 3.2.9 on 2022-01-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_dogs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
